train_set:
    NAME: duet
    music_root: '/home/verma198/Public/dualflow/data_split/music'
    motion_root: '/home/verma198/Public/dualflow/data_split/motion'
    text_root: '/home/verma198/Public/dualflow/data_split/text'
    MOTION_REP: global
    MODE: train
    CACHE: True
    music_rep: 'jukebox'

val_set:
    NAME: duet
    music_root: '/home/verma198/Public/dualflow/data_split/music'
    motion_root: '/home/verma198/Public/dualflow/data_split/motion'
    text_root: '/home/verma198/Public/dualflow/data_split/text'
    MOTION_REP: global
    MODE: val
    CACHE: True
    music_rep: 'jukebox'

test_set:
    NAME: duet
    music_root: '/home/verma198/Public/dualflow/data_split/music'
    motion_root: '/home/verma198/Public/dualflow/data_split/motion'
    text_root: '/home/verma198/Public/dualflow/data_split/text'
    MOTION_REP: global
    MODE: test
    CACHE: True
    music_rep: 'jukebox'

# train_set:
#     NAME: duet
#     music_root: '/depot/natallah/data/shourya/data_split/music'
#     motion_root: '/depot/natallah/data/shourya/data_split/motion'
#     text_root: '/depot/natallah/data/shourya/data_split/text'
#     MOTION_REP: global
#     MODE: train
#     CACHE: True
#     music_rep: 'jukebox'

# val_set:
#     NAME: duet
#     music_root: '/depot/natallah/data/shourya/data_split/music'
#     motion_root: '/depot/natallah/data/shourya/data_split/motion'
#     text_root: '/depot/natallah/data/shourya/data_split/text'
#     MOTION_REP: global
#     MODE: val
#     CACHE: True
#     music_rep: 'jukebox'

# test_set:
#     NAME: duet
#     music_root: '/depot/natallah/data/shourya/data_split/music'
#     motion_root: '/depot/natallah/data/shourya/data_split/motion'
#     text_root: '/depot/natallah/data/shourya/data_split/text'
#     MOTION_REP: global
#     MODE: test
#     CACHE: True
#     music_rep: 'jukebox'