NAME: DuetModel
NUM_LAYERS: 20

# NAME: ReactModel
# NUM_LAYERS: 4

NUM_HEADS: 8
DROPOUT: 0.1
INPUT_DIM: 262
LATENT_DIM: 512
FF_SIZE: 1024
MUSIC_DIM: 4800
ACTIVATION: gelu
CHECKPOINT: /home/verma198/model=DuetModel-epoch=2199-step=13200.ckpt

DIFFUSION_STEPS: 200
BETA_SCHEDULER: cosine
SAMPLER: uniform

# Retrieval configuration
RETRIEVAL_FILE: /home/verma198/Public/dualflow/dance/data/data_new.npz

MOTION_REP: global
FINETUNE: False

TEXT_ENCODER: clip
T_BAR: 200

CONTROL: text
STRATEGY: ddim50
CFG_WEIGHT: 3.5

USE_TEXT: True
USE_MUSIC: True