# ==============================================================================
# train_enhanced_duet_debug.yaml  
# Enhanced version of your original train_duet_debug.yaml
# ==============================================================================

GENERAL:
  EXP_NAME: enhanced_duet20_both_juke    # New experiment name
  CHECKPOINT: ./checkpoints
  LOG_DIR: ./log

TRAIN:
  # === EXISTING PARAMETERS (keep same) ===
  LR: 2e-4                     # Keep your learning rate
  WARMPUP_STEPS: 1000          # Keep same
  WEIGHT_DECAY: 0.00002        # Keep same  
  BATCH_SIZE: 32               # Keep same (or reduce if memory issues)
  EPOCH: 5000                  # Keep same
  LOG_STEPS: 10                # Keep same
  SAVE_STEPS: 20000            # Keep same
  SAVE_EPOCH: 100              # Keep same
  NUM_WORKERS: 8               # Keep same
  LAST_EPOCH: 0                # Keep same
  LAST_ITER: 0                 # Keep same
  
  # Resume from existing checkpoint if you want to continue training
  RESUME: #checkpoints/react20_both_juke/model/last.ckpt
  
  # === NEW RETRIEVAL-SPECIFIC PARAMETERS ===
  
  # Retrieval training phases
  RETRIEVAL_WARMUP_EPOCHS: 5   # Train without retrieval for first 5 epochs
  RETRIEVAL_LOSS_WEIGHT: 1.0   # Weight for retrieval loss component
  PROGRESSIVE_RETRIEVAL: True   # Gradually increase retrieval influence
  
  # Database preparation
  PREPARE_DATABASE: True        # Auto-prepare database if not exists
  DATABASE_BATCH_SIZE: 16       # Batch size for database preparation (lower to save memory)
  
  # Enhanced training strategies  
  MIXED_CONDITIONING: True      # Use mixed conditioning during training
  CONDITIONING_DROPOUT: 0.1     # Randomly drop conditioning for robustness
  
  # Memory optimization
  GRADIENT_CHECKPOINTING: False # Enable if you run out of memory
  CACHE_DATABASE: True          # Cache retrieval results for speed

# Training command:
# python train_enhanced_duet.py --model_cfg configs/model_enhanced_duet_debug.yaml --train_cfg configs/train_enhanced_duet_debug.yaml --data_cfg configs/datasets_duet.yaml
